---
title: "CoverageAnalysis"
author: "Enrico"
date: "July 2018"
output: html_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, cache = FALSE, results = "hide"
)


```

# Foreword  

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE
  ,results='hide')
memory.limit(size = 24000)


```

```{r load_libraries, echo=FALSE}
require(dplyr)
require(quanteda)
require(readtext)
require(knitr)

```



```{r source_files, echo=FALSE }

# source("01_globals.R")
source("02_pred_classes.R")
# source("ev_nlp_eda_lib.R")

fulldata <- T
silent <- T
# eda_re_init()
```



## Temp

Date: `r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`   
Full Data: `r fulldata`

    
```{r physical_analysis_ls, echo = FALSE, results ='markup'}
require(kableExtra)

# invisible(rie(phys_an_df,physicalAnalysis,data_dir_corpus_full))
#phys_an_df$file <- gsub("_?subset.*\\.", ".", phys_an_df$file)
#row.names(phys_an_df) <- NULL
#phys_an_df %>%  kable(row.names = FALSE) %>% kable_styling()
```


# 1 gram coverage
```{r 1gram_plot, echo = FALSE, results='markup'}

invisible(gc())

invisible(produce_ngram_bare_dtf())

o_1grams_basic <- DTF_Basic$new(dtf_1gram_sep)
plots <- o_1grams_basic$coverageGraphs()


grid.arrange(plots[[1]], plots[[2]],nrow = 1)

```
coverage table
```{r 1gram_table, echo = FALSE, results='markup'}
o_1grams_basic$print_coverage()

```



# 2 gram coverage
```{r 2gram, echo = FALSE, results='markup'}


o_2grams_basic <- DTF_Basic$new(dtf_2gram_sep)
plots <- o_2grams_basic$coverageGraphs()


grid.arrange(plots[[1]], plots[[2]],nrow = 1)

```
coverage table
```{r 2gram_table, echo = FALSE, results='markup'}
o_2grams_basic$print_coverage()

```



# 3 gram coverage
```{r 3gram, echo = FALSE, results='markup'}


o_3grams_basic <- DTF_Basic$new(dtf_3gram_sep)
plots <- o_3grams_basic$coverageGraphs()


grid.arrange(plots[[1]], plots[[2]],nrow = 1)

```
coverage table
```{r 3gram_table, echo = FALSE, results='markup'}
o_3grams_basic$print_coverage()

```




# N Features
```{r nfeat_ngrams, echo = FALSE, results='markup'}

mydf <- data.frame(nfeatures = c(
  o_1grams_basic$nfeat()
    ,o_2grams_basic$nfeat()
    ,o_3grams_basic$nfeat()
))

p<-ggplot(data=mydf, aes(x=seq_along(nfeatures), y=nfeatures)) +
  geom_bar(stat="identity")
p

```

